config/routes.rb
Series::Application.routes.draw do

  match '/series/:serie_title/capitles/:season/:capitle_order' =>  "capitles#show",
        :as => :serie_capitle

  resources :series do
      resources :capitles
  end

  resources :user_sessions
  resources :users

  match '/home' => 'series#home'
  match '/catalog/:letter' => 'series#index', :as => :catalog_letter
  match '/catalog' => 'series#index'

  root :to => "series#index"

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  # GET /series
  # GET /series.xml
  def index
    series = Serie.where(nil)
    series = series.with_letter(params[:letter]) unless params[:letter].blank?
    @series = series.all
    #paginar si no es filtrado por letra
    @series = @series.paginate :page => params[:page], :per_page => 16 if params[:letter].blank?

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @series }
    end
  end

  def home
    @series = Serie.all.paginate :page => params[:page], :per_page => 16

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /series/1
  # GET /series/1.xml
  def show
    title = CGI.unescape(params[:id])
    @serie = Serie.titled(title).first

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @series }
    end
  end

 
end

app/helpers/series_helper.rb
module SeriesHelper

  def simple_link_to_serie(serie)
    link_to serie.title, series_path( h(serie.title)), :class => 'serie_link'
  end

  def serie_info_panel(serie)
    content_tag :div, :id =>'serie_info_panel' do
      "<p id='serie_title'><b>#{serie.title}</b></p>
       <p id='serie_description'>
         <b>Description:</b>
         #{serie.description}
       </p>".html_safe+
        serie_seasons_and_capitles_info(serie)
    end
  end

  def serie_seasons_and_capitles_info(serie)
    content_tag :div, :id=>'serie_seasons_and_capitles_info' do
      "<b>Seasons:</b> #{ serie.seasons_count }, <b>capitles: </b>#{ serie.capitles_count }".html_safe
    end
  end
end

app/views/series/_catalog.html.erb
<div id="catalog" >

  <%= catalog_header %>
  <div id="catalog_body">
    <div id="letter_filter_side_bar">
      <%=  letter_filter_links_sidebar %>
    </div>
    <div id="catalog_series_list_container">
      <% series.in_groups_of(3).each do |n_series_group| %>
        <div class="catalog_link_container_row">
          <% n_series_group.compact.each do |serie|%>
            <div class="catalog_link_container clickable_container">
              <%= simple_link_to_serie(serie) %>
            </div>
          <% end %>
        </div>
      <% end %>

      <%if params[:letter].blank?%>
        <%= page_entries_info(series) %>
        <%= catalog_previous_results_link(series) unless series.current_page == 1 %>
        <%= catalog_next_results_link(series) unless series.current_page == series.total_pages %>
      <%end%>
    </div>

  </div>

</div>

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :seasons_count %><br />
    <%= f.text_field :seasons_count %>
  </div>
  <div class="field">
    <%= f.label :capitles_count %><br />
    <%= f.text_field :capitles_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/_serie_capitles_by_season_container.erb
<div class="season_capitles_container">
  <table>
    <tr>
      <th>Temporada <%= season %></th>
    </tr>
    <% capitles.each do |capitle| %>
      <tr>
        <td>
          <%= link_to "#{capitle.order}- #{capitle.title}",
                      serie_capitle_path(capitle.serie.title, capitle.season, capitle.order),
                      :class => "capitle_link" %>
        </td>
      </tr>
    <%  end %>
  </table>
</div>

app/views/series/_serie_capitles_by_season_panel.html.erb
<div class="season_capitles_container">
  <div class="season_capitles_container_header">
    <h3>Temporada <%= season %></h3>
  </div>
  <div class="season_capitles_container_body">
    <% capitles.each do |capitle| %>
      <div class="clickable_container">
        <%= link_to "#{capitle.order}- #{capitle.title}",
          serie_capitle_path(capitle.serie.title, capitle.season, capitle.order),
          :class => "capitle_link" %>
      </div>
    <%  end %>
  </div>
</div>

app/views/series/_serie_panel.erb
<div id="serie_panel_container" class="content">
  <%=serie_info_panel(serie)%>

  <div id="serie_capitles_by_season_panel_contanier">
    <% 1.upto serie.seasons_count do |season| %>
      <%= render :partial => 'serie_capitles_by_season_panel',
                 :locals => {:season => season, :capitles => serie.capitles.for_season(season)} %>
    <%end%>
  </div>


</div>

app/views/series/home.html.erb
<h1>Home</h1>
<h3>Listing series</h3>

<table>
  <% @series.tabletize(3).each do |n_series_group| %>
    <tr>
      <% n_series_group.compact.each do |serie|%>
        <td><%= simple_link_to_serie(serie) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

app/views/series/index.html.erb
<h1>Listing series</h1>

<%= render :partial => 'catalog', :locals => {:series => @series} %>
<br />

app/views/series/show.html.erb
<%= render :partial => 'serie_panel', :locals => {:serie => @serie} %>

<%= link_to 'Back', series_index_path %>