config/routes.rb
Series::Application.routes.draw do

  match '/series/:serie_title/capitles/:season/:capitle_order' =>  "capitles#show",
        :as => :serie_capitle

  resources :series do
      resources :capitles
  end

  resources :user_sessions
  resources :users

  match '/home' => 'series#home'
  match '/catalog/:letter' => 'series#index', :as => :catalog_letter
  match '/catalog' => 'series#index'

  root :to => "series#index"

end

app/models/capitle.rb
class Capitle < ActiveRecord::Base
  belongs_to :serie

  has_many :videos
  
  before_create :update_serie_season_count_if_needed, :increment_serie_capitles_count

  #parameterized named scopes
  class<<self
    def for_season(season_num)
      where(:season => season_num)
    end

    def season_capitle(season,capitle)
      for_season(season).where(:order => capitle).first
    end
  end

  private
  def update_serie_season_count_if_needed
    serie.update_attribute(:seasons_count, season) unless serie.seasons_count >= season
  end

  def increment_serie_capitles_count
    serie.increment! :capitles_count
  end


end

app/controllers/capitles_controller.rb
class CapitlesController < ApplicationController
  before_filter :load_parent_serie

  # GET /capitles
  # GET /capitles.xml
  def index
    @capitles = Capitle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @capitles }
    end
  end

  # GET /capitles/1
  # GET /capitles/1.xml
  def show
    @capitle = @serie.capitles.for_season(params[:season]).
                where(:order => params[:capitle_order]).first

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @capitle }
    end
  end

  private

  def load_parent_serie
    if not params[:serie_title].blank?
      @serie = Serie.titled(params[:serie_title]).first
    end
  end
end

app/helpers/capitles_helper.rb
module CapitlesHelper
  
  def capitle_content_header
    content_tag :div, :id => "capitle_content_header" do
      (%w(Videos Photos Links All).collect do |content_type|
          content_tag :div, :class => "clickable_container capitle_content_header_tab" do
            link_to_function content_type, "alert('#{content_type}');"
          end
        end).join(" ").html_safe
    end
  end

end

app/views/capitles/_capitle_available_video_panel.html.erb
<div id="capitle_available_videos_panel_container">
  <div id="online_video_container">
    <% capitle.videos.online.each do |online_video| %>
      <%= link_to "View", online_video.url, :class => 'video_link online_video' %>
    <%end%>
  </div>
  <div id="download_video_container">
    <% capitle.videos.downloads.each do |download_video| %>
      <%= link_to "View", download_video.url, :class => 'video_link download_video' %>
    <%end%>

  </div>

</div>

app/views/capitles/_capitle_video_content.html.erb
<div class="capitle_content_item">
  <div class="capitle_content_item_icon">
    <%= image_tag  "rails.png" %>
  </div>
  <div class="capitle_content_item_info">
    <div class="capitle_content_item_description"><%= video.description || "Descripción"%></div>

    <div class="capitle_content_item_languaje_and_subtitles" >Languaje: <%= video.languaje %>, subtitles: <%= video.subtitles || "no"  %> </div>
    <div class="capitle_content_item_url clickable_container">
      <%= link_to video.url, video.url %>
    </div>
  </div>
  <div class="capitle_content_item_social_actions">
    <%= image_tag  "like_button.jpg"%>
  </div>
</div>

app/views/capitles/_form.html.erb
<%= form_for(@capitle) do |f| %>
  <% if @capitle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@capitle.errors.count, "error") %> prohibited this capitle from being saved:</h2>

      <ul>
      <% @capitle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :serie %><br />
    <%= f.text_field :serie %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/capitles/edit.html.erb
<h1>Editing capitle</h1>

<%= render 'form' %>

<%= link_to 'Show', @capitle %> |
<%= link_to 'Back', capitles_path %>

app/views/capitles/index.html.erb
<h1>Listing capitles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Serie</th>
    <th>Season</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @capitles.each do |capitle| %>
  <tr>
    <td><%= capitle.title %></td>
    <td><%= capitle.serie %></td>
    <td><%= capitle.season %></td>
    <td><%= capitle.order %></td>
    <td><%= link_to 'Show', capitle %></td>
    <td><%= link_to 'Edit', edit_capitle_path(capitle) %></td>
    <td><%= link_to 'Destroy', capitle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Capitle', new_capitle_path %>

app/views/capitles/new.html.erb
<h1>New capitle</h1>

<%= render 'form' %>

<%= link_to 'Back', capitles_path %>

app/views/capitles/show.html.erb
<div id="capitle_panel_container">
  <p><%= @serie.title %>: season <%= @capitle.season %>, capitle <%= @capitle.order %></p>
  <p><%= @capitle.title %> </p>

  <div id="capitle_content_container">
    <%=  capitle_content_header %>
    <div id="capitle_content_body">
     <% @capitle.videos.each do |video| %>
        <%= render :partial => 'capitle_video_content', :locals => {:video => video} %>
     <%  end %>
    </div>
  </div>
</div>